name = "FgankModsList"
author = "lre0550"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b28e752a34327c1ffb48dcecba8704680eec7ecccc375c8b19b9d04c7bf04f4"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
