name = "FgankModsList"
author = "lre0550"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6df657918a87331708390440ca7aed0280efdf708031af7825d218adc7481aeb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
